name: toast_plus
description: A customizable toast notification package for Flutter with advanced features and great design.
version: 1.0.0
homepage: https://github.com/KhaledAl2mri/toast_plus

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.k2.toast_plus
        pluginClass: ToastPlusPlugin
      ios:
        pluginClass: ToastPlusPlugin
      web:
        pluginClass: ToastPlusPlugin
      macos:
        pluginClass: ToastPlusPlugin
      windows:
        pluginClass: ToastPlusPlugin
      linux:
        pluginClass: ToastPlusPlugin

  # You can add assets, fonts, and other configurations as needed.
  # Example:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
