name: toast_plus
description: A customizable toast notification package for Flutter with advanced features and great design.
version: 1.0.0
homepage: https://github.com/KhaledAl2mri/toast_plus

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  # You can add other development dependencies here

flutter:
  plugin:
    platforms:
      android:
        package: com.k2.toast_plus
        pluginClass: ToastPlusPlugin
      ios:
        pluginClass: ToastPlusPlugin

  # The following section is specific to Flutter.
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# You can specify your own categorization of dependencies
# dependencies:
#   flutter:
#     sdk: flutter

# You can also specify optional, transitive dependencies here
# dependency_overrides:
#   analyzer:
#     path: ../analyzer
